#!/bin/sh
#set -x
check_inter="10s"
while true; do
	sleep $check_inter
	#date
	a="$(ps | grep single-board-test | grep -v 'grep single-board-test')"
	if [ -z "$a" ] ; then
		/etc/init.d/cgminer.sh restart
	fi
done
